// Package postgres implements the ledger domain interfaces using PostgreSQL.
//
// In production, this package is generated by sqlc from
// internal/repository/postgres/queries/*.sql. For this scaffold, we
// provide a manually-written equivalent that uses the same query SQL
// and produces type-safe code via pgx directly. Once sqlc is installed
// (see Makefile target `sqlc-gen`), regenerate to get the official output.
//
// To regenerate with sqlc:
//   make sqlc-gen
//
// The hand-written functions in this file are kept aligned with what
// sqlc would produce, so swapping between manual and generated is
// straightforward.
package postgres

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgxpool"

	apperrors "github.com/runut/fmcg-wallet/internal/platform/errors"
)

// =============================================================================
// DTOs — what the database returns
// =============================================================================
//
// These are intentionally separate from the domain entities (which are in
// internal/domain/ledger) so that:
//  1. The DB schema can evolve without leaking to the domain layer
//  2. We can map between snake_case (DB) and CamelCase (Go) here
//  3. Test mocks can use domain types directly
//
// sqlc would generate these automatically; we write them by hand for the
// scaffold so we can run tests without first installing sqlc.

// AccountDTO mirrors the accounts table.
type AccountDTO struct {
	ID            uuid.UUID
	Code          string
	Name          string
	Type          string
	Status        string
	Currency      string
	CachedBalance int64
	OwnerID       *uuid.UUID
	TenantID      uuid.UUID
	Metadata      []byte // raw JSON
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

// TransactionDTO mirrors the transactions table.
type TransactionDTO struct {
	ID             uuid.UUID
	IdempotencyKey string
	Status         string
	Description    *string
	RefType        *string
	RefID          *uuid.UUID
	InitiatorID    *uuid.UUID
	TenantID       uuid.UUID
	PeriodID       uuid.UUID
	Metadata       []byte
	PostedAt       *time.Time
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

// EntryDTO mirrors the ledger_entries table.
type EntryDTO struct {
	ID            uuid.UUID
	TransactionID uuid.UUID
	AccountID     uuid.UUID
	Amount        int64
	Type          string
	RefType       *string
	RefID         *uuid.UUID
	PeriodID      uuid.UUID
	Description   *string
	Currency      string
	Metadata      []byte
	CreatedAt     time.Time

	// Hash chain (Fase 1C — added by migration 000007).
	PrevHash  string
	EntryHash string
}

// TrialBalanceDTO is the global reconciler result.
type TrialBalanceDTO struct {
	TotalDebit  int64
	TotalCredit int64
	Imbalance   int64
}

// =============================================================================
// Public types used by repositories
// =============================================================================

// PgxTx is the type used for transactions in repository methods. Alias
// for pgx.Tx so external callers (main.go, use cases) don't import pgx
// directly. Repos internally type-assert ledger.Tx to pgx.Tx.
type PgxTx = pgx.Tx

// =============================================================================
// DB connection wrapper
// =============================================================================

// DB is a thin wrapper over pgxpool.Pool that provides typed access to
// our domain repositories. One DB per application instance.
type DB struct {
	Pool *pgxpool.Pool
}

// NewDB creates a new DB with the given pool. Pool tuning happens
// in cmd/api/main.go.
func NewDB(pool *pgxpool.Pool) *DB {
	return &DB{Pool: pool}
}

// Close releases the pool.
func (db *DB) Close() {
	if db.Pool != nil {
		db.Pool.Close()
	}
}

// =============================================================================
// Common query helpers — shared scan/conversion logic
// =============================================================================

// scanAccount reads one row from a SELECT against the accounts table.
func scanAccount(row pgx.Row) (AccountDTO, error) {
	var a AccountDTO
	err := row.Scan(
		&a.ID, &a.Code, &a.Name, &a.Type, &a.Status, &a.Currency,
		&a.CachedBalance, &a.OwnerID, &a.TenantID, &a.Metadata,
		&a.CreatedAt, &a.UpdatedAt,
	)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return AccountDTO{}, apperrors.ErrAccountNotFound
		}
		return AccountDTO{}, fmt.Errorf("scan account: %w", err)
	}
	return a, nil
}

// scanTransaction reads one row from transactions.
func scanTransaction(row pgx.Row) (TransactionDTO, error) {
	var t TransactionDTO
	err := row.Scan(
		&t.ID, &t.IdempotencyKey, &t.Status, &t.Description, &t.RefType, &t.RefID,
		&t.InitiatorID, &t.TenantID, &t.PeriodID, &t.Metadata, &t.PostedAt,
		&t.CreatedAt, &t.UpdatedAt,
	)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return TransactionDTO{}, apperrors.ErrNotFound
		}
		return TransactionDTO{}, fmt.Errorf("scan transaction: %w", err)
	}
	return t, nil
}

// isUniqueViolation checks if an error is a Postgres unique-constraint violation.
func isUniqueViolation(err error) bool {
	var pgErr *pgconn.PgError
	if errors.As(err, &pgErr) {
		return pgErr.Code == "23505" // unique_violation
	}
	return false
}

// isCheckViolation checks for a check-constraint violation (e.g. immutability trigger).
func isCheckViolation(err error) bool {
	var pgErr *pgconn.PgError
	if errors.As(err, &pgErr) {
		return pgErr.Code == "23514" // check_violation
	}
	return false
}

// jsonRaw returns a []byte for an arbitrary value (always non-nil).
func jsonRaw(v any) []byte {
	if v == nil {
		return []byte("{}")
	}
	b, err := json.Marshal(v)
	if err != nil {
		return []byte("{}")
	}
	return b
}

// jsonString returns a human-readable representation (for logs).
func jsonString(b []byte) string {
	if len(b) == 0 {
		return "{}"
	}
	return string(b)
}

// parseMetadata unmarshals a metadata column. Returns empty map on nil.
func parseMetadata(b []byte) map[string]any {
	if len(b) == 0 {
		return map[string]any{}
	}
	var out map[string]any
	if err := json.Unmarshal(b, &out); err != nil {
		return map[string]any{}
	}
	if out == nil {
		return map[string]any{}
	}
	return out
}

// runInTx executes fn inside a transaction with the given options.
// On any error returned by fn, the transaction is rolled back.
//
// IMPORTANT: All ledger operations MUST go through this. Never call
// ledger repos with the bare pool.
func (db *DB) runInTx(ctx context.Context, opts pgx.TxOptions, fn func(pgx.Tx) error) error {
	tx, err := db.Pool.BeginTx(ctx, opts)
	if err != nil {
		return fmt.Errorf("begin tx: %w", err)
	}
	defer func() {
		_ = tx.Rollback(ctx) // no-op if Commit already succeeded
	}()

	if err := fn(tx); err != nil {
		return err
	}

	if err := tx.Commit(ctx); err != nil {
		return fmt.Errorf("commit tx: %w", err)
	}
	return nil
}

// ReadCommitted is the default isolation level for our transactions.
// We use it (not Serializable) because:
//  1. Our locking is done via SELECT FOR UPDATE, not isolation alone
//  2. Serializable has significant retry overhead in Postgres
//  3. ReadCommitted + explicit locks = correct & performant
var defaultTxOpts = pgx.TxOptions{IsoLevel: pgx.ReadCommitted}

// RunInTx is the public entry point. Uses default isolation.
// Exposed so main.go and use cases can wrap business logic in a tx.
func (db *DB) RunInTx(ctx context.Context, fn func(pgx.Tx) error) error {
	return db.runInTx(ctx, defaultTxOpts, fn)
}

// executeTx is an unexported alias kept for compatibility with internal callers.
func (db *DB) executeTx(ctx context.Context, fn func(pgx.Tx) error) error {
	return db.RunInTx(ctx, fn)
}
