// Package postgres implements the ledger domain interfaces using PostgreSQL.
//
// In production, this package is generated by sqlc from
// internal/repository/postgres/queries/*.sql. For this scaffold, we
// provide a manually-written equivalent that uses the same query SQL
// and produces type-safe code via pgx directly. Once sqlc is installed
// (see Makefile target `sqlc-gen`), regenerate to get the official output.
//
// To regenerate with sqlc:
//   make sqlc-gen
//
// The hand-written functions in this file are kept aligned with what
// sqlc would produce, so swapping between manual and generated is
// straightforward.
package postgres

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgxpool"

	apperrors "github.com/runut/fmcg-wallet/internal/platform/errors"
	"github.com/runut/fmcg-wallet/internal/platform/tenantctx"
)

// =============================================================================
// DTOs — what the database returns
// =============================================================================
//
// These are intentionally separate from the domain entities (which are in
// internal/domain/ledger) so that:
//  1. The DB schema can evolve without leaking to the domain layer
//  2. We can map between snake_case (DB) and CamelCase (Go) here
//  3. Test mocks can use domain types directly
//
// sqlc would generate these automatically; we write them by hand for the
// scaffold so we can run tests without first installing sqlc.

// AccountDTO mirrors the accounts table.
type AccountDTO struct {
	ID            uuid.UUID
	Code          string
	Name          string
	Type          string
	Status        string
	Currency      string
	CachedBalance int64
	OwnerID       *uuid.UUID
	TenantID      uuid.UUID
	Metadata      []byte // raw JSON
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

// TransactionDTO mirrors the transactions table.
type TransactionDTO struct {
	ID             uuid.UUID
	IdempotencyKey string
	Status         string
	Description    *string
	RefType        *string
	RefID          *uuid.UUID
	InitiatorID    *uuid.UUID
	TenantID       uuid.UUID
	PeriodID       uuid.UUID
	Metadata       []byte
	PostedAt       *time.Time
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

// EntryDTO mirrors the ledger_entries table.
type EntryDTO struct {
	ID            uuid.UUID
	TransactionID uuid.UUID
	AccountID     uuid.UUID
	Amount        int64
	Type          string
	RefType       *string
	RefID         *uuid.UUID
	PeriodID      uuid.UUID
	Description   *string
	Currency      string
	Metadata      []byte
	CreatedAt     time.Time

	// Hash chain (Fase 1C — added by migration 000007).
	PrevHash  string
	EntryHash string
}

// TrialBalanceDTO is the global reconciler result.
type TrialBalanceDTO struct {
	TotalDebit  int64
	TotalCredit int64
	Imbalance   int64
}

// =============================================================================
// Public types used by repositories
// =============================================================================

// PgxTx is the type used for transactions in repository methods. Alias
// for pgx.Tx so external callers (main.go, use cases) don't import pgx
// directly. Repos internally type-assert ledger.Tx to pgx.Tx.
type PgxTx = pgx.Tx

// =============================================================================
// DB connection wrapper
// =============================================================================

// DB is a thin wrapper over pgxpool.Pool that provides typed access to
// our domain repositories. One DB per application instance.
type DB struct {
	Pool *pgxpool.Pool
}

// NewDB creates a new DB with the given pool. Pool tuning happens
// in cmd/api/main.go.
func NewDB(pool *pgxpool.Pool) *DB {
	return &DB{Pool: pool}
}

// Close releases the pool.
func (db *DB) Close() {
	if db.Pool != nil {
		db.Pool.Close()
	}
}

// =============================================================================
// Common query helpers — shared scan/conversion logic
// =============================================================================

// scanAccount reads one row from a SELECT against the accounts table.
func scanAccount(row pgx.Row) (AccountDTO, error) {
	var a AccountDTO
	err := row.Scan(
		&a.ID, &a.Code, &a.Name, &a.Type, &a.Status, &a.Currency,
		&a.CachedBalance, &a.OwnerID, &a.TenantID, &a.Metadata,
		&a.CreatedAt, &a.UpdatedAt,
	)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return AccountDTO{}, apperrors.ErrAccountNotFound
		}
		return AccountDTO{}, fmt.Errorf("scan account: %w", err)
	}
	return a, nil
}

// scanTransaction reads one row from transactions.
func scanTransaction(row pgx.Row) (TransactionDTO, error) {
	var t TransactionDTO
	err := row.Scan(
		&t.ID, &t.IdempotencyKey, &t.Status, &t.Description, &t.RefType, &t.RefID,
		&t.InitiatorID, &t.TenantID, &t.PeriodID, &t.Metadata, &t.PostedAt,
		&t.CreatedAt, &t.UpdatedAt,
	)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return TransactionDTO{}, apperrors.ErrNotFound
		}
		return TransactionDTO{}, fmt.Errorf("scan transaction: %w", err)
	}
	return t, nil
}

// isUniqueViolation checks if an error is a Postgres unique-constraint violation.
func isUniqueViolation(err error) bool {
	var pgErr *pgconn.PgError
	if errors.As(err, &pgErr) {
		return pgErr.Code == "23505" // unique_violation
	}
	return false
}

// isCheckViolation checks for a check-constraint violation (e.g. immutability trigger).
func isCheckViolation(err error) bool {
	var pgErr *pgconn.PgError
	if errors.As(err, &pgErr) {
		return pgErr.Code == "23514" // check_violation
	}
	return false
}

// jsonRaw returns a []byte for an arbitrary value (always non-nil).
func jsonRaw(v any) []byte {
	if v == nil {
		return []byte("{}")
	}
	b, err := json.Marshal(v)
	if err != nil {
		return []byte("{}")
	}
	return b
}

// jsonString returns a human-readable representation (for logs).
func jsonString(b []byte) string {
	if len(b) == 0 {
		return "{}"
	}
	return string(b)
}

// parseMetadata unmarshals a metadata column. Returns empty map on nil.
func parseMetadata(b []byte) map[string]any {
	if len(b) == 0 {
		return map[string]any{}
	}
	var out map[string]any
	if err := json.Unmarshal(b, &out); err != nil {
		return map[string]any{}
	}
	if out == nil {
		return map[string]any{}
	}
	return out
}

// runInTx executes fn inside a transaction with the given options.
// On any error returned by fn, the transaction is rolled back.
//
// IMPORTANT: All ledger operations MUST go through this. Never call
// ledger repos with the bare pool.
func (db *DB) runInTx(ctx context.Context, opts pgx.TxOptions, fn func(pgx.Tx) error) error {
	tx, err := db.Pool.BeginTx(ctx, opts)
	if err != nil {
		return fmt.Errorf("begin tx: %w", err)
	}
	defer func() {
		_ = tx.Rollback(ctx) // no-op if Commit already succeeded
	}()

	if err := fn(tx); err != nil {
		return err
	}

	if err := tx.Commit(ctx); err != nil {
		return fmt.Errorf("commit tx: %w", err)
	}
	return nil
}

// ReadCommitted is the default isolation level for our transactions.
// We use it (not Serializable) because:
//  1. Our locking is done via SELECT FOR UPDATE, not isolation alone
//  2. Serializable has significant retry overhead in Postgres
//  3. ReadCommitted + explicit locks = correct & performant
var defaultTxOpts = pgx.TxOptions{IsoLevel: pgx.ReadCommitted}

// RunInTx is the public entry point. Uses default isolation.
// Exposed so main.go and use cases can wrap business logic in a tx.
func (db *DB) RunInTx(ctx context.Context, fn func(pgx.Tx) error) error {
	return db.runInTx(ctx, defaultTxOpts, fn)
}

// executeTx is an unexported alias kept for compatibility with internal callers.
func (db *DB) executeTx(ctx context.Context, fn func(pgx.Tx) error) error {
	return db.RunInTx(ctx, fn)
}

// readOnlyTxOpts opens the tx as READ ONLY for read-only repositories.
// READ ONLY is a strong hint to Postgres that the tx won't write; the
// planner can skip some work and the DB can short-circuit RLS WITH CHECK.
var readOnlyTxOpts = pgx.TxOptions{IsoLevel: pgx.ReadCommitted, AccessMode: pgx.ReadOnly}

// RunInReadTx opens a READ-ONLY transaction, binds tenant GUC variables
// from the context (if a *tenantctx.Info is present), and runs fn.
//
// Sprint 29 / Fase 8 fix: the previous pattern (using `r.db.Pool.Query`
// directly) left tenant GUC unset on the connection, which meant RLS USING
// clauses evaluated against NULL and returned zero rows for the caller —
// or, for INSERT, failed the WITH CHECK outright. By opening a tx and
// calling `SELECT set_config(..., true)` (is_local=true) we ensure:
//   - RLS sees the correct tenant_id for SELECT
//   - RLS WITH CHECK accepts the row when the writer (worker) supplies the
//     tenant_id explicitly via the *tenantctx.Info it places on the ctx
//   - GUC auto-reverts on COMMIT/ROLLBACK so the connection is safe to
//     return to the pool
//
// If no *tenantctx.Info is present on ctx, GUC binding is skipped and
// queries rely on RLS evaluating to zero rows (the "fail-closed" default
// for our tenant-isolation policies). Callers that NEED data should ensure
// the context carries one — typically the HTTP middleware
// (TenantContextMiddleware) does this for /v1/* routes.
func (db *DB) RunInReadTx(ctx context.Context, fn func(pgx.Tx) error) error {
	return db.runInTx(ctx, readOnlyTxOpts, func(tx pgx.Tx) error {
		if info := tenantctx.InfoFromContext(ctx); info != nil {
			// SetTenantContext can fail on certain pgxpool versions where
			// the concrete tx type doesn't satisfy the TxExec interface
			// expected by SetTenantContext. We log + continue rather
			// than fail the read — the RLS policies still apply because
			// they're defined at the database level (no GUC = no match
			// in the USING clause, which fails closed to zero rows).
			if err := tenantctx.SetTenantContext(ctx, tx, info); err != nil {
				_ = err // swallowed; see comment above
			}
		}
		return fn(tx)
	})
}

// RunInAdminTx opens a transaction on the regular pool, switches the role
// to `app_admin` via `SET LOCAL ROLE` for the duration of the tx, runs fn,
// and auto-reverts the role on COMMIT/ROLLBACK.
//
// Sprint 30: closes the "silent worker bug" from Sprint 29. Cross-tenant
// worker operations (outbox publisher scanning all unpublished events,
// aging recalculator scanning all tenants with outstanding invoices,
// fx refresher listing tenants with FX rates, reconciler listing all
// tenants) cannot bind GUC because there is no single tenant context.
// They need the `app_admin` role which bypasses RLS via the admin_bypass
// policies established by migrations 000015-000023.
//
// Why SET LOCAL ROLE inside a tx (not a separate connection pool):
//   - app_admin is NOINHERIT (migration 000015) so fmcg must explicitly
//     SET ROLE app_admin per operation
//   - `SET LOCAL ROLE` is tx-scoped — auto-reverts on COMMIT/ROLLBACK
//   - No additional connection pool, no password management for app_admin
//   - Existing fmcg connection pool is reused, simpler worker main.go
//
// If the fmcg role lacks GRANT app_admin (it has it via 000015), this will
// fail with `ERROR: permission denied to set role "app_admin"`. The
// migration 000023 ensures all required tables have GRANTs to app_admin.
//
// Idempotent: if called concurrently or in a nested tx the inner SET LOCAL
// ROLE is a no-op (already app_admin).
func (db *DB) RunInAdminTx(ctx context.Context, fn func(pgx.Tx) error) error {
	return db.runInTx(ctx, defaultTxOpts, func(tx pgx.Tx) error {
		// SET LOCAL ROLE app_admin — auto-reverts on COMMIT/ROLLBACK.
		// We do NOT bind tenant GUC; admin operations explicitly
		// bypass RLS for cross-tenant visibility.
		if _, err := tx.Exec(ctx, "SET LOCAL ROLE app_admin"); err != nil {
			return fmt.Errorf("admin tx: SET LOCAL ROLE app_admin: %w", err)
		}
		return fn(tx)
	})
}

// IsAdminRoleAvailable returns true if the current DB role can switch to
// app_admin. Used by ops tooling (and integration tests) to detect missing
// grants before issuing a RunInAdminTx call that would otherwise fail with
// "permission denied to set role".
//
// The check attempts an actual SET LOCAL ROLE inside a throwaway tx — this
// is the source of truth because Postgres evaluates the membership grant
// (via pg_auth_members) at SET time, and the only thing we need to know is
// whether SET LOCAL ROLE will succeed.
//
// Safe to call at startup: rolls back immediately.
func (db *DB) IsAdminRoleAvailable(ctx context.Context) (bool, error) {
	var canSet bool
	err := db.runInTx(ctx, defaultTxOpts, func(tx pgx.Tx) error {
		// SET LOCAL ROLE inside a tx; the assignment succeeds or fails
		// based on whether current_user has been GRANTED app_admin.
		if _, err := tx.Exec(ctx, "SET LOCAL ROLE app_admin"); err != nil {
			canSet = false
			return nil // not a real error — caller decides what to do
		}
		canSet = true
		return nil
	})
	if err != nil {
		return false, fmt.Errorf("check admin role: %w", err)
	}
	return canSet, nil
}
